language: php
sudo: required
php:
    - 5.6
    - 7.0

script: phpunit --coverage-text

env:
    - SYMFONY_VERSION="2.8.*"
    - SYMFONY_VERSION="3.1.*"

install:
    - composer require symfony/filesystem:${SYMFONY_VERSION}
    - composer update $COMPOSER_FLAGS
